SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS customer_item;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS item;
SET REFERENTIAL_INTEGRITY TRUE;
CREATE TABLE customer_item (tempBarnacleGenerator varchar(1));
ALTER TABLE customer_item ADD COLUMN (customerIdPart1 VARCHAR(255) NOT NULL);
ALTER TABLE customer_item ADD COLUMN (customerIdPart2 VARCHAR(255) NOT NULL);
ALTER TABLE customer_item ADD COLUMN (itemId1 VARCHAR(255) NOT NULL);
ALTER TABLE customer_item ADD COLUMN (itemId2 VARCHAR(255) NOT NULL);
ALTER TABLE customer_item DROP COLUMN tempBarnacleGenerator;
ALTER TABLE customer_item ADD PRIMARY KEY (customerIdPart1, customerIdPart2, itemId1, itemId2);
CREATE TABLE customer (tempBarnacleGenerator varchar(1));
ALTER TABLE customer ADD COLUMN (id_part_1 VARCHAR(255) NOT NULL);
ALTER TABLE customer ADD COLUMN (id_part_2 VARCHAR(255) NOT NULL);
ALTER TABLE customer ADD COLUMN (name VARCHAR(255));
ALTER TABLE customer DROP COLUMN tempBarnacleGenerator;
ALTER TABLE customer ADD PRIMARY KEY (id_part_1, id_part_2);
CREATE TABLE item (tempBarnacleGenerator varchar(1));
ALTER TABLE item ADD COLUMN (id1 VARCHAR(255) NOT NULL);
ALTER TABLE item ADD COLUMN (id2 VARCHAR(255) NOT NULL);
ALTER TABLE item ADD COLUMN (description VARCHAR(255));
ALTER TABLE item DROP COLUMN tempBarnacleGenerator;
ALTER TABLE item ADD PRIMARY KEY (id1, id2);
ALTER TABLE customer_item ADD CONSTRAINT fk_customer FOREIGN KEY (customerIdPart1, customerIdPart2) REFERENCES customer (id_part_1, id_part_2);
ALTER TABLE customer_item ADD CONSTRAINT fk_item FOREIGN KEY (itemId1, itemId2) REFERENCES item (id1, id2);
