SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS user_table;
SET REFERENTIAL_INTEGRITY TRUE;
CREATE TABLE address (tempBarnacleGenerator varchar(1));
ALTER TABLE address ADD COLUMN (userId VARCHAR(255) NOT NULL);
ALTER TABLE address ADD COLUMN (email VARCHAR(255));
ALTER TABLE address DROP COLUMN tempBarnacleGenerator;
ALTER TABLE address ADD PRIMARY KEY (userId);
CREATE TABLE user_table (tempBarnacleGenerator varchar(1));
ALTER TABLE user_table ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE user_table ADD COLUMN (userName VARCHAR(255));
ALTER TABLE user_table DROP COLUMN tempBarnacleGenerator;
ALTER TABLE user_table ADD PRIMARY KEY (id);
ALTER TABLE address ADD CONSTRAINT fk_address_1 FOREIGN KEY (userId) REFERENCES user_table (id);
