SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS object_types;
DROP TABLE IF EXISTS basic_types;
SET REFERENTIAL_INTEGRITY TRUE;
CREATE TABLE object_types (tempBarnacleGenerator varchar(1));
ALTER TABLE object_types ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE object_types ADD COLUMN (my_boolean TINYINT);
ALTER TABLE object_types ADD COLUMN (my_int INTEGER);
ALTER TABLE object_types ADD COLUMN (my_long BIGINT);
ALTER TABLE object_types ADD COLUMN (my_float DOUBLE);
ALTER TABLE object_types ADD COLUMN (my_double DOUBLE);
ALTER TABLE object_types ADD COLUMN (my_byte TINYINT);
ALTER TABLE object_types ADD COLUMN (my_short SMALLINT);
ALTER TABLE object_types DROP COLUMN tempBarnacleGenerator;
ALTER TABLE object_types ADD PRIMARY KEY (id);
CREATE TABLE basic_types (tempBarnacleGenerator varchar(1));
ALTER TABLE basic_types ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE basic_types ADD COLUMN (my_boolean TINYINT);
ALTER TABLE basic_types ADD COLUMN (my_int INTEGER);
ALTER TABLE basic_types ADD COLUMN (my_long BIGINT);
ALTER TABLE basic_types ADD COLUMN (my_float DOUBLE);
ALTER TABLE basic_types ADD COLUMN (my_double DOUBLE);
ALTER TABLE basic_types ADD COLUMN (my_byte TINYINT);
ALTER TABLE basic_types ADD COLUMN (my_short SMALLINT);
ALTER TABLE basic_types DROP COLUMN tempBarnacleGenerator;
ALTER TABLE basic_types ADD PRIMARY KEY (id);
