SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS customer_item;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS item;
SET REFERENTIAL_INTEGRITY TRUE;
CREATE TABLE customer_item (tempBarnacleGenerator varchar(1));
ALTER TABLE customer_item ADD COLUMN (customerId VARCHAR(255) NOT NULL);
ALTER TABLE customer_item ADD COLUMN (itemId VARCHAR(255) NOT NULL);
ALTER TABLE customer_item DROP COLUMN tempBarnacleGenerator;
ALTER TABLE customer_item ADD PRIMARY KEY (customerId, itemId);
CREATE TABLE customer (tempBarnacleGenerator varchar(1));
ALTER TABLE customer ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE customer ADD COLUMN (name VARCHAR(255));
ALTER TABLE customer DROP COLUMN tempBarnacleGenerator;
ALTER TABLE customer ADD PRIMARY KEY (id);
CREATE TABLE item (tempBarnacleGenerator varchar(1));
ALTER TABLE item ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE item ADD COLUMN (description VARCHAR(255));
ALTER TABLE item DROP COLUMN tempBarnacleGenerator;
ALTER TABLE item ADD PRIMARY KEY (id);
ALTER TABLE customer_item ADD CONSTRAINT fk_customer FOREIGN KEY (customerId) REFERENCES customer (id);
ALTER TABLE customer_item ADD CONSTRAINT fk_item FOREIGN KEY (itemId) REFERENCES item (id);
