//// DO NOT CHANGE THIS FILE MANUALLY!
//package de.arthurpicht.barnacleGeneratorTest.tc_01.persistence.dao;
//
//import de.arthurpicht.barnacleGeneratorTest.connectionManager.ConnectionManager;
//import de.arthurpicht.barnacleGeneratorTest.connectionManager.DataSourceException;
//import de.arthurpicht.barnacleGeneratorTest.connectionManager.EntityNotFoundException;
//import de.arthurpicht.barnacleGeneratorTest.tc_07.persistence.vo.PersonVO;
//import org.slf4j.Logger;
//import org.slf4j.LoggerFactory;
//
//import java.sql.*;
//import java.util.ArrayList;
//import java.util.List;
//
///**
// * Generated by Barnacle Version 0.3.0-SNAPSHOT (2023-02-12) on 13.03.2023 09:35:08
// * https://github.com/arthurpicht/Barnacle
// * created 2007 - 2023 by Arthur Picht, Düren and Düsseldorf, Germany
// *
// * DO NOT CHANGE THIS FILE MANUALLY!
// */
//public class PersonDAOPrep {
//
//	private static final Logger logger = LoggerFactory.getLogger(PersonDAOPrep.class);
//
//	private static final String CREATE_STATEMENT = "INSERT INTO person (id, userName, favoriteGarmentId) VALUES (?, ?, ?)";
//	private static final String LOAD_STATEMENT = "SELECT * FROM person WHERE id = ?";
//	private static final String DELETE_STATEMENT = "DELETE FROM person WHERE id = ?";
//	private static final String UPDATE_STATEMENT = "UPDATE person SET userName = ?, favoriteGarmentId = ? WHERE id = ?";
//	private static final String FIND_ALL_STATEMENT = "SELECT * FROM person";
//	private static final String FK_PERSON_1_STATEMENT = "SELECT * FROM person WHERE favoriteGarmentId = ?";
//	private static final String UK_FAV_GARMENT = "SELECT * FROM person WHERE favoriteGarmentId = ?";
//
//	public static void create(PersonVO personVO) throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			create(personVO, connection);
//		} catch (SQLException sqlEx) {
//			throw new DataSourceException(sqlEx);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static void create(PersonVO personVO, Connection connection) throws SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(CREATE_STATEMENT);
//		preparedStatement.setString(1, personVO.getId());
//		preparedStatement.setString(2, personVO.getUserName());
//		preparedStatement.setString(3, personVO.getFavoriteGarmentId());
//		logger.debug(CREATE_STATEMENT + " [" + personVO.getId() + "][" + personVO.getUserName() + "][" + personVO.getFavoriteGarmentId() + "]");
//		preparedStatement.executeUpdate();
//		try { preparedStatement.close(); } catch (SQLException ignored) {}
//	}
//
//	public static void create(List<PersonVO> personVOs) throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			create(personVOs, connection);
//		} catch (SQLException sqlEx) {
//			throw new DataSourceException(sqlEx);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static void create(List<PersonVO> personVOs, Connection connection) throws SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(CREATE_STATEMENT);
//		for (PersonVO personVO : personVOs) {
//			preparedStatement.setString(1, personVO.getId());
//			preparedStatement.setString(2, personVO.getUserName());
//			preparedStatement.setString(3, personVO.getFavoriteGarmentId());
//			logger.debug(CREATE_STATEMENT + " [" + personVO.getId() + "][" + personVO.getUserName() + "][" + personVO.getFavoriteGarmentId() + "]");
//			preparedStatement.addBatch();
//		}
//		preparedStatement.executeBatch();
//		try { preparedStatement.close(); } catch (SQLException ignored) {}
//	}
//
//	public static PersonVO load(String id) throws DataSourceException, EntityNotFoundException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			return load(id, connection);
//		} catch(SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static PersonVO load(String id, Connection connection) throws SQLException, EntityNotFoundException {
//		PreparedStatement preparedStatement = connection.prepareStatement(LOAD_STATEMENT);
//		preparedStatement.setString(1, id);
//		logger.debug(LOAD_STATEMENT + " [" + id + "]");
//		ResultSet resultSet = preparedStatement.executeQuery();
//		try {
//			if (resultSet.next()) {
//				PersonVO personVO = new PersonVO(id);
//				personVO.setUserName(resultSet.getString("userName"));
//				personVO.setFavoriteGarmentId(resultSet.getString("favoriteGarmentId"));
//				return personVO;
//			} else {
//				throw new EntityNotFoundException("Entity 'person' with primary key field 'id' = [" + id + "] not found!");
//			}
//		} finally {
//			if (resultSet != null) { try { resultSet.close(); } catch (SQLException ignored) {}}
//			try { preparedStatement.close(); } catch (SQLException ignored) {}
//		}
//	}
//
//	public static void delete(String id) throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			delete(id, connection);
//		} catch (SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static void delete(String id, Connection connection) throws SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(DELETE_STATEMENT);
//		preparedStatement.setString(1, id);
//		logger.debug(DELETE_STATEMENT + " [" + id + "]");
//		preparedStatement.execute();
//		try { preparedStatement.close(); } catch (SQLException ignored) {}
//	}
//
//	public static void update(PersonVO personVO) throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			update(personVO, connection);
//		} catch (SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static void update(PersonVO personVO, Connection connection) throws SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(UPDATE_STATEMENT);
//		preparedStatement.setString(1, personVO.getUserName());
//		preparedStatement.setString(2, personVO.getFavoriteGarmentId());
//		preparedStatement.setString(3, personVO.getId());
//		logger.debug(UPDATE_STATEMENT + " [" + personVO.getUserName() + "][" + personVO.getFavoriteGarmentId() + "][" + personVO.getId() + "]");
//		preparedStatement.executeUpdate();
//		try { preparedStatement.close(); } catch (SQLException ignored) {}
//	}
//
//	public static List<PersonVO> findAll() throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			return findAll(connection);
//		} catch (SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static List<PersonVO> findAll(Connection connection) throws SQLException {
//		Statement statement = connection.createStatement();
//		logger.debug(FIND_ALL_STATEMENT);
//		ResultSet resultSet = statement.executeQuery(FIND_ALL_STATEMENT);
//		List<PersonVO> personVOs = new ArrayList<>();
//		try {
//			while (resultSet.next()) {
//				String id = resultSet.getString("id");
//				String userName = resultSet.getString("userName");
//				String favoriteGarmentId = resultSet.getString("favoriteGarmentId");
//				PersonVO personVO = new PersonVO(id);
//				personVO.setUserName(userName);
//				personVO.setFavoriteGarmentId(favoriteGarmentId);
//				personVOs.add(personVO);
//			}
//			return personVOs;
//		} finally {
//			if (resultSet != null) { try { resultSet.close(); } catch (SQLException ignored) {}}
//			try { statement.close(); } catch (SQLException ignored) {}
//		}
//	}
//
//	public static List<PersonVO> findByFk_person_1(String favoriteGarmentId) throws DataSourceException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			return findByFk_person_1(favoriteGarmentId, connection);
//		} catch (SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static List<PersonVO> findByFk_person_1(String favoriteGarmentId, Connection connection) throws SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(FK_PERSON_1_STATEMENT);
//		preparedStatement.setString(1, favoriteGarmentId);
//		logger.debug(FK_PERSON_1_STATEMENT + " [" + favoriteGarmentId + "]");
//		ResultSet resultSet = preparedStatement.executeQuery();
//		List<PersonVO> personVOList = new ArrayList<>();
//		try {
//			while (resultSet.next()) {
//				String id = resultSet.getString("id");
//				String userName = resultSet.getString("userName");
//				PersonVO personVO = new PersonVO(id);
//				personVO.setUserName(userName);
//				personVO.setFavoriteGarmentId(favoriteGarmentId);
//				personVOList.add(personVO);
//			}
//			return personVOList;
//		} finally {
//			if (resultSet != null) { try { resultSet.close(); } catch (SQLException ignored) {}}
//			try { preparedStatement.close(); } catch (SQLException ignored) {}
//		}
//	}
//
//	public static PersonVO findByUk_favoriteGarmentId(String favoriteGarmentId) throws DataSourceException, EntityNotFoundException {
//		Connection connection = ConnectionManager.openConnection(PersonDAOPrep.class);
//		try {
//			return findByUk_favoriteGarmentId(favoriteGarmentId, connection);
//		} catch (SQLException e) {
//			throw new DataSourceException(e);
//		} finally {
//			ConnectionManager.releaseConnection(connection, PersonDAOPrep.class);
//		}
//	}
//
//	public static PersonVO findByUk_favoriteGarmentId(String favoriteGarmentId, Connection connection) throws EntityNotFoundException, SQLException {
//		PreparedStatement preparedStatement = connection.prepareStatement(FK_PERSON_1_STATEMENT);
//		preparedStatement.setString(1, favoriteGarmentId);
//		logger.debug(FK_PERSON_1_STATEMENT + " [" + favoriteGarmentId + "]");
//		ResultSet resultSet = preparedStatement.executeQuery();
//		try {
//			if (resultSet.next()) {
//				String id = resultSet.getString("id");
//				String userName = resultSet.getString("userName");
//				PersonVO personVO = new PersonVO(id);
//				personVO.setUserName(userName);
//				personVO.setFavoriteGarmentId(favoriteGarmentId);
//				return personVO;
//			} else {
//				throw new EntityNotFoundException("person-Entity with unique key 'uk_favoriteGarmentId'[favoriteGarmentId = " + favoriteGarmentId + "] does not exist!");
//			}
//		} finally {
//			if (resultSet != null) { try { resultSet.close(); } catch (SQLException ignored) {}}
//			try { preparedStatement.close(); } catch (SQLException ignored) {}
//		}
//	}
//
//	private static String getValueExpression(Object o, String sqlType) {
//		if (o == null) { return "NULL"; }
//		if (sqlType.startsWith("VARCHAR") || sqlType.equals("DATE")) { return "'" + o + "'"; }
//		return "" + o;
//	}
//
//}
