SET REFERENTIAL_INTEGRITY FALSE;
DROP TABLE IF EXISTS person;
SET REFERENTIAL_INTEGRITY TRUE;
CREATE TABLE person (tempBarnacleGenerator varchar(1));
ALTER TABLE person ADD COLUMN (id VARCHAR(255) NOT NULL);
ALTER TABLE person ADD COLUMN (first_name VARCHAR(255));
ALTER TABLE person ADD COLUMN (last_name VARCHAR(255));
ALTER TABLE person DROP COLUMN tempBarnacleGenerator;
ALTER TABLE person ADD PRIMARY KEY (id);
